#############################################################################
# Makefile for building: OTNImplantsDemo
# Generated by qmake (3.1) (Qt 6.8.2)
# Project:  OTNImplantsDemo.pro
# Template: app
# Command: C:/msys64/mingw64/bin/qmake6.exe -o Makefile OTNImplantsDemo.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:/msys64/mingw64/bin/qmake6.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
QINSTALL      = C:/msys64/mingw64/bin/qmake6.exe -install qinstall
QINSTALL_PROGRAM = C:/msys64/mingw64/bin/qmake6.exe -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
IDC           = idc
IDL           = widl
ZIP           = 
DEF_FILE      = 
RES_FILE      = 
SED           = sed
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: OTNImplantsDemo.pro ../../../mingw64/share/qt6/mkspecs/win32-g++/qmake.conf ../../../mingw64/share/qt6/mkspecs/features/spec_pre.prf \
		../../../mingw64/share/qt6/mkspecs/features/device_config.prf \
		../../../mingw64/share/qt6/mkspecs/common/sanitize.conf \
		../../../mingw64/share/qt6/mkspecs/common/gcc-base.conf \
		../../../mingw64/share/qt6/mkspecs/common/g++-base.conf \
		../../../mingw64/share/qt6/mkspecs/features/win32/windows_vulkan_sdk.prf \
		../../../mingw64/share/qt6/mkspecs/common/windows-vulkan.conf \
		../../../mingw64/share/qt6/mkspecs/common/g++-win32.conf \
		../../../mingw64/share/qt6/mkspecs/common/windows-desktop.conf \
		../../../mingw64/share/qt6/mkspecs/qconfig.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_ext_openxr_loader.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3danimation.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dcore.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dextras.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dinput.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquick.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickscene3d.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickscene3d_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3drender.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_activeqt.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_activeqt_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_axbase_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_axserver.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_axserver_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_charts.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_charts_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_core.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_core_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_dbus.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_designer.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_entrypoint_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_grpc.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_grpc_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_grpcquick.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_grpcquick_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_gui.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_help.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_help_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_httpserver.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_httpserver_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labsplatform.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_languageserver_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_linguist.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_location.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_location_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_network.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_network_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_networkauth.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_nfc.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_opengl.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_positioning.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobuf.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobuf_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobufqtcoretypes.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobufqtcoretypes_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobufqtguitypes.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobufqtguitypes_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobufquick.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobufquick_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobufwellknowntypes.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobufwellknowntypes_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qml.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlmeta.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dphysics.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dxr.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2windowsstyleimpl.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2windowsstyleimpl_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_repparser.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_scxml.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_scxmlqml.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_sensors.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_sensorsquick.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_serialbus.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_serialport.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_sql.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_statemachine.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_statemachine_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_statemachineqml.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_svg.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_testlib.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_uitools.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_websockets.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_webview.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_webview_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_webviewquick.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_widgets.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_xml.pri \
		../../../mingw64/share/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		../../../mingw64/share/qt6/mkspecs/features/qt_functions.prf \
		../../../mingw64/share/qt6/mkspecs/features/qt_config.prf \
		../../../mingw64/share/qt6/mkspecs/win32-g++/qmake.conf \
		../../../mingw64/share/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../mingw64/share/qt6/mkspecs/features/exclusive_builds.prf \
		../../../mingw64/share/qt6/mkspecs/features/toolchain.prf \
		../../../mingw64/share/qt6/mkspecs/features/default_pre.prf \
		../../../mingw64/share/qt6/mkspecs/features/win32/default_pre.prf \
		../../../mingw64/share/qt6/mkspecs/features/resolve_config.prf \
		../../../mingw64/share/qt6/mkspecs/features/exclusive_builds_post.prf \
		../../../mingw64/share/qt6/mkspecs/features/default_post.prf \
		../../../mingw64/share/qt6/mkspecs/features/lrelease.prf \
		../../../mingw64/share/qt6/mkspecs/features/precompile_header.prf \
		../../../mingw64/share/qt6/mkspecs/features/warn_on.prf \
		../../../mingw64/share/qt6/mkspecs/features/permissions.prf \
		../../../mingw64/share/qt6/mkspecs/features/qt.prf \
		../../../mingw64/share/qt6/mkspecs/features/resources_functions.prf \
		../../../mingw64/share/qt6/mkspecs/features/resources.prf \
		../../../mingw64/share/qt6/mkspecs/features/moc.prf \
		../../../mingw64/share/qt6/mkspecs/features/win32/opengl.prf \
		../../../mingw64/share/qt6/mkspecs/features/uic.prf \
		../../../mingw64/share/qt6/mkspecs/features/qmake_use.prf \
		../../../mingw64/share/qt6/mkspecs/features/file_copies.prf \
		../../../mingw64/share/qt6/mkspecs/features/win32/windows.prf \
		../../../mingw64/share/qt6/mkspecs/features/testcase_targets.prf \
		../../../mingw64/share/qt6/mkspecs/features/exceptions.prf \
		../../../mingw64/share/qt6/mkspecs/features/yacc.prf \
		../../../mingw64/share/qt6/mkspecs/features/lex.prf \
		OTNImplantsDemo.pro \
		../../../mingw64/lib/Qt6EntryPoint.prl \
		../../../mingw64/share/qt6/mkspecs/features/build_pass.prf
	$(QMAKE) -o Makefile OTNImplantsDemo.pro
../../../mingw64/share/qt6/mkspecs/features/spec_pre.prf:
../../../mingw64/share/qt6/mkspecs/features/device_config.prf:
../../../mingw64/share/qt6/mkspecs/common/sanitize.conf:
../../../mingw64/share/qt6/mkspecs/common/gcc-base.conf:
../../../mingw64/share/qt6/mkspecs/common/g++-base.conf:
../../../mingw64/share/qt6/mkspecs/features/win32/windows_vulkan_sdk.prf:
../../../mingw64/share/qt6/mkspecs/common/windows-vulkan.conf:
../../../mingw64/share/qt6/mkspecs/common/g++-win32.conf:
../../../mingw64/share/qt6/mkspecs/common/windows-desktop.conf:
../../../mingw64/share/qt6/mkspecs/qconfig.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_ext_openxr_loader.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3danimation.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dcore.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dextras.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dinput.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dlogic.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquick.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickscene3d.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3dquickscene3d_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3drender.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_3drender_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_activeqt.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_activeqt_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_axbase_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_axcontainer.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_axserver.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_axserver_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_bluetooth.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_charts.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_charts_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_chartsqml.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_concurrent.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_core.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_core5compat.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_core5compat_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_core_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_datavisualization.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_datavisualizationqml.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_dbus.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_designer.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_designer_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_entrypoint_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_example_icons_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_grpc.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_grpc_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_grpcquick.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_grpcquick_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_gui.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_gui_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_help.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_help_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_httpserver.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_httpserver_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_jsonrpc_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labsplatform.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labssettings.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labssettings_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_languageserver_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_linguist.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_location.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_location_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_multimedia.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_network.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_network_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_networkauth.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_nfc.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_nfc_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_opengl.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_positioning.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_positioning_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_positioningquick.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_printsupport.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobuf.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobuf_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobufqtcoretypes.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobufqtcoretypes_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobufqtguitypes.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobufqtguitypes_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobufquick.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobufquick_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobufwellknowntypes.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_protobufwellknowntypes_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qml.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qml_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlassetdownloader.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmldom_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlls_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlmeta.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmltest.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3d.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3d_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3deffects.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dphysics.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dutils.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dxr.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick3dxr_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quick_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2windowsstyleimpl.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrols2windowsstyleimpl_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicktimeline.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_repparser.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_repparser_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_scxml.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_scxml_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_scxmlqml.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_scxmlqml_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_sensors.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_sensors_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_sensorsquick.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_serialbus.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_serialport.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_serialport_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_shadertools.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_shadertools_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_spatialaudio.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_sql.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_sql_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_statemachine.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_statemachine_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_statemachineqml.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_statemachineqml_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_svg.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_svg_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_testlib.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_texttospeech.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_tools_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_uitools.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_uitools_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_webchannel.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_webchannelquick.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_websockets.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_websockets_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_webview.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_webview_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_webviewquick.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_webviewquick_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_widgets.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_xml.pri:
../../../mingw64/share/qt6/mkspecs/modules/qt_lib_xml_private.pri:
../../../mingw64/share/qt6/mkspecs/features/qt_functions.prf:
../../../mingw64/share/qt6/mkspecs/features/qt_config.prf:
../../../mingw64/share/qt6/mkspecs/win32-g++/qmake.conf:
../../../mingw64/share/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../mingw64/share/qt6/mkspecs/features/exclusive_builds.prf:
../../../mingw64/share/qt6/mkspecs/features/toolchain.prf:
../../../mingw64/share/qt6/mkspecs/features/default_pre.prf:
../../../mingw64/share/qt6/mkspecs/features/win32/default_pre.prf:
../../../mingw64/share/qt6/mkspecs/features/resolve_config.prf:
../../../mingw64/share/qt6/mkspecs/features/exclusive_builds_post.prf:
../../../mingw64/share/qt6/mkspecs/features/default_post.prf:
../../../mingw64/share/qt6/mkspecs/features/lrelease.prf:
../../../mingw64/share/qt6/mkspecs/features/precompile_header.prf:
../../../mingw64/share/qt6/mkspecs/features/warn_on.prf:
../../../mingw64/share/qt6/mkspecs/features/permissions.prf:
../../../mingw64/share/qt6/mkspecs/features/qt.prf:
../../../mingw64/share/qt6/mkspecs/features/resources_functions.prf:
../../../mingw64/share/qt6/mkspecs/features/resources.prf:
../../../mingw64/share/qt6/mkspecs/features/moc.prf:
../../../mingw64/share/qt6/mkspecs/features/win32/opengl.prf:
../../../mingw64/share/qt6/mkspecs/features/uic.prf:
../../../mingw64/share/qt6/mkspecs/features/qmake_use.prf:
../../../mingw64/share/qt6/mkspecs/features/file_copies.prf:
../../../mingw64/share/qt6/mkspecs/features/win32/windows.prf:
../../../mingw64/share/qt6/mkspecs/features/testcase_targets.prf:
../../../mingw64/share/qt6/mkspecs/features/exceptions.prf:
../../../mingw64/share/qt6/mkspecs/features/yacc.prf:
../../../mingw64/share/qt6/mkspecs/features/lex.prf:
OTNImplantsDemo.pro:
../../../mingw64/lib/Qt6EntryPoint.prl:
../../../mingw64/share/qt6/mkspecs/features/build_pass.prf:
qmake: FORCE
	@$(QMAKE) -o Makefile OTNImplantsDemo.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

.SUFFIXES:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
